import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/Header/Header";
import { CartProvider } from "./(context)/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartProvider>
      <html lang="en">
        <body className={inter.className}>
          <MainHeader />
          <main className="max-w-[84rem] mx-auto bg-[#0F1117]">{children}</main>
        </body>
      </html>
    </CartProvider>
  );
}
